---
resources:
- name: input
  type: git
  source:
    uri: https://github.com/SergeyMuha/concourse-dora-push.git
#    uri: https://github.com/ihuston/python-cf-examples.git

- name: resource-deploy-web-app
  type: cf
  source:
    api: https://api.gcp.sergeymuha.altoros.com
    username: admin
    password: eoqn5vln91htjki9wk4q
    organization: altoros
    space: altoros
    skip_cert_check: true

jobs:
- name: job-first
  public: true
  plan:
  - get: input
  - task: first
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      inputs:
      - name: input
      run:
        dir: input
        path: ls
        args: ['* ../output/']
        path: ./untar.sh
      outputs:
      - name: output
#  - task: second
#    config:
#      platform: linux
#      image_resource:
#        type: docker-image
#        source: {repository: ubuntu}
#      inputs:
#      - name: output
#      run:
#        dir: files
#        path: ls
#        args: [-laR]

  - put: resource-deploy-web-app
    params:
#      path: input/02-pydata-spyre-app/
      path: output/app/
      manifest: output/app/manifest.yml
#      manifest: input/02-pydata-spyre-app/manifest.yml
#      current_app_name: doranew
