---
resources:
- name: files
  type: git
  source:
    uri: https://github.com/SergeyMuha/concoure-dora-push.git

jobs:
- name: job-first
  public: true
  plan:
  - get: files
  - task: first
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      inputs:
      - name: files
      run:
        dir: files
        path: ls
        args: ['-ltr'] 
        #dir: arch
        #path: untar.sh
#        args: [dora-droplet.tar.gz]
#        args: [-zxvf dora-droplet.tar.gz]
